mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
serial: {}
advanced:
  log_level: info
  channel: 11
  network_key: GENERATE
  pan_id: GENERATE
  ext_pan_id: GENERATE
frontend:
  enabled: true
  port: 8080
  host: 0.0.0.0
homeassistant:
  enabled: true
onboarding: true
