mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: debug
  channel: 11
  network_key:
    - 54
    - 162
    - 51
    - 205
    - 90
    - 216
    - 6
    - 98
    - 98
    - 33
    - 209
    - 107
    - 151
    - 2
    - 55
    - 81
  pan_id: 10998
  ext_pan_id:
    - 136
    - 40
    - 51
    - 126
    - 199
    - 134
    - 107
    - 110
permit_join: true
frontend:
  port: 8080
  host: 0.0.0.0
  enabled: true
homeassistant:
  enabled: true
onboarding: true
version: 4
